### ISSUE TITLE
☂ Migration path to this controller

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/firewall-controller-manager#1]
- The old firewall-controller does not understand the new v2 API, therefore we need to deploy the v1 `Firewall` resource into the shoot as long as there are firewall-controllers not being aware of the v2 API
  - We cannot drop the v1 `Firewall` deployment to the shoot in the GEPM until then

## The Migration

- The old code in the GEPM for managing the firewall is deleted such that the FCM can take over the management of the firewall
- We do not want to lose the existing firewall though
- So, in the values provider of the GEPM, the GEPM checks if a firewall with the `cluster.metal-stack.io/id` and without the `metal.stack.io/firewall-controller-manager/set` tag is present for the project
- If this is the case, it creates a `Firewall` v2 resource with the name of the firewall (`shoot--...-firewall-...`) in the seed's shoot namespace along with the `Firewall` v1 deployment in the shoot
- The FCM requires a feature to adopt a firewall (similar to adoption of a pod by a replica set), such that it takes over an existing firewall without creating a new one
  - For this, we need to add object metadata to the firewall `template` (similar to `replicaset.spec.metadata`) and a `selector` to the `FirewallSet`
  - On reconciliation of a set, it selects firewalls using this selector and if it finds resources without an owner reference, it tries to adopt this firewall, which works as follows:
    - The set controller adds an owner reference to the firewall resource
    -  And updates the tags of the firewall with the `metal.stack.io/firewall-controller-manager/set` annotation (so on next reconcile of the GEPM, it will not see a missing firewall anymore)
    - It will then continue the regular reconcile (will not trigger a scale up anymore as it now already has an owned `Firewall` resource)
- The migration is now done, however the controller will show "NotConnected", leading to an unhealthy set because the corresponding `FirewallMonitor` is not updated by the firewall-controller
  - Thus, before deploying the FCM, we need to release a firewall-controller version that is aware of `FirewallMonitor`s and roll it out across the fleet
  - When it finds a single monitor in the `firewall` namespace, it updates the monitor with the same details it already uses to update the `Firewall` v1 resource
  - If it finds multiple monitors, it does not do anything (this can occur when the first rolling update is getting issued)
 - Alternative: Add an annotation to the `firewall-migrated-<short-hash>` like `metal.stack.io/firewall-controller-manager/no-controller-connection`, marking the firewall set healthy without requiring a controller to update the controller status field (advantage: no fleet rollout required, disadvantage: status is not observed and reflected)

## TODO

- [x] Implement adoption
- [x] Integration test the adoption
- [x] Implement `FirewallMonitor` update for firewall-controller

**Comment by majst01** [comment]
Lets discuss this in person, my feeling is that we simple should avoid doing a migration from v1 to v2 but only support replace the existing firewall machine with a new one with the new mechanism.

**Comment by Gerrit91** [comment]
Yep, let's discuss it. I already started implementation yesterday afternoon though, we can still decide if we want to use it or not.

**Comment by Gerrit91** [comment]
Was implemented this way.
