### ISSUE TITLE
Migration Path of the firewall-controller

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/firewall-controller-manager#3]
With #2, we achieved that firewalls provisioned by the GEPM can be adopted by the firewall-controller-manager without having to recreate them. The FCM can then further manage the lifecycle of these firewalls.

For the firewall-controller there are also some considerations taken into account in order to achieve a seamless transition.

## Update / Downgrade Constraints

The firewall-controller-manager deploys firewalls with userdata that contains a kubeconfig to communicate with the seed instead of the shoot. Due to this architectural change, we need to put some constraints onto updates and downgrades for the firewall-controller:

1. The FCM has to prevent rolling updates for firewall-controllers with versions `< v2.0.0`. It cannot construct kubeconfigs for older firewall-controller versions and it is also not feasible to implement this because we want to have rotating shoot kubeconfigs, which expire regularly.
1. Due to this constraint, all firewalls with a version `< v2.0.0` are adopted.
1. firewall-controllers with a version `>= v2.0.0` have to prevent a downgrade to a firewall-controller `< v2.0.0`, as the older version cannot find a `Firewall/v1` resource in the seed.
    - As a result the integration test toggling up- and downgrade of the controller in the integration test suite must be excluded for the new major version.

## Migration to firewall-controller v2.0.0

We cannot expect from the users to recreate all firewalls for getting firewall-controller `>= v2.0.0` as the landscape is too big and users will need a long transition period for rolling their firewalls.

Therefore, we also need to introduce a way to update an existing firewall-controller from version `< v2.0.0` to a version `>= v2.0.0`.

This can be achieved in the following way:

1. The firewall-controller `v2.0.0` has to implement a search for a `Firewall/v2` resource with the kubeconfig it starts with. If it's a firewall deployed through the firewall-controller-manager, it will find this resource and the controller can start right away.
1. If the firewall-controller does not find a `Firewall/v2` resource, it checks whether it's still running with the shoot client as provisioned earlier by the GEPM. It can figure this out by searching for the migration secret described in the next point.
1. For firewalls that do not put a firewall-controller version in the `Firewall/v2` resource (meaning they have never started and communicated with the seed), the firewall-controller-manager deploys a migration secret containing the seed kubeconfig into the `firewall` namespace of the shoot cluster. This should not be a problem for security because the permissions of this kubeconfig are very limited, but should be discussed.
1. If a migration secret is found, it will test if a client connection can be made with this kubeconfig and if it can find a `Firewall/v2` resource with it. If this is the case, it exchanges the kubeconfig file on the disk with the new kubeconfig and restart.

**Comment by majst01** [comment]
Firewall-Controller is at `v1.2.2` ?

**Comment by Gerrit91** [comment]
Thanks, corrected.
